repo_url: https://github.com/flanksource/canary-checker/
repo_name: Canary Checker
site_name: Canary Checker
theme: material
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - codehilite:
      linenums: true
nav:
  - Installation: ./installation.md
  - CLI:
      - run: ./cli/canary-checker_run.md
      - serve: ./cli/canary-checker_serve.md
  - Checks: ./reference.md
