apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: docker-pass
spec:
  interval: 30
  dockerPush:
    - image: docker.io/flanksource/busybox:1.30
      username: test
      password: foobar
    - image: ttl.sh/flanksource-busybox:not-found-tag
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
