apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-fail
spec:
  interval: 30
  http:
    - endpoint: https://ttpstat.us/500
      thresholdMillis: 3000
      responseCodes: [201, 200, 301]
      responseContent: ""
      maxSSLExpiry: 60
    - endpoint: https://httpstat.us/500
      thresholdMillis: 3000
      responseCodes: [201, 200, 301]
      responseContent: ""
      maxSSLExpiry: 60
