name: Publish Binary
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools
    steps:
      - uses: actions/checkout@master
      - run: ./release.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
