name: Publish Binary
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:0.6
    steps:
      - uses: actions/checkout@master
      - run: ./release.sh
        env:
          TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
