name: Publish Docs
on: [push]
jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools
    steps:
      - uses: actions/checkout@master
      - run: make build-api-docs build-docs deploy-docs
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}

---
name: Publish Binary
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools
    steps:
      - uses: actions/checkout@master
      - run: ./release.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
